# Generated by Django 5.0.14 on 2026-02-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('era', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('usage', models.TextField(blank=True)),
                ('vr_scene', models.CharField(blank=True, max_length=100)),
                ('vr_scene_info', models.JSONField(blank=True, default=dict)),
                ('captured_image', models.TextField()),
                ('restored_image', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
