# Generated by Django 5.0.14 on 2026-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='design_3d_image',
            field=models.TextField(blank=True),
        ),
    ]
